#!/usr/bin/env php
<?php
declare(strict_types=1);

foreach([__DIR__.'/../vendor/autoload.php', __DIR__.'/../../vendor/autoload.php'] as $autoloader) {
  if (\file_exists($autoloader)) {
    define('INSTALLED_AUTOLOAD_EXCEPTION_PATH', $autoloader);
  }
}

if (!defined('INSTALLED_AUTOLOAD_EXCEPTION_PATH')) {
  
}

require INSTALLED_AUTOLOAD_EXCEPTION_PATH;

Modassir\Exception\Exception::argv($argv)->run();
?>